### ISSUE TITLE
Feature request: Ability to remove sudo

### ISSUE THREAD

**Issue by a13x212** [opscode-cookbooks/sudo#48]
The ability to remove sudo access if it exist. 

Example:
sudo 'developers' do
  group      'developers'
  nopasswd   true
  action remove
end

**Comment by autotune** [comment]
Looks like that just removes it if you have it in /etc/sudoers.d, not ideal for RHEL at least.

**Comment by jtimberman** [comment]
The `sudo` resource manages `/etc/sudoers.d/` files. There is no capability to manage entries in the `/etc/sudoers` file though, because we have no possible way of knowing what those might be. The `default` recipe in this cookbook will manage `/etc/sudoers` entirely, and has attributes that can be used to manage specific access. Your best bet would be to use that, or otherwise manage the `/etc/sudoers` template in your own cookbook.
